version: "3"
services:
  main_nginx:
    image: nginx:1.13.12-alpine
    depends_on:
      - jona
      - elija
      - tobito
      - files_nginx
    volumes:
      - ./main-nginx.conf.template:/etc/nginx/conf.d/default.conf.template
      - ${LETSENCRYPT_DIR}:/etc/letsencrypt
    env_file: ./nginx.env
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
  neo4j:
    image: neo4j:3.4.5
    deploy:
      replicas: ${NEO4J_REPLICAS}
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 800M
    environment:
      - NEO4J_AUTH=none
    volumes:
      - $NEO4J_DIR:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    deploy:
      replicas: ${ELASTICSEARCH_REPLICAS}
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 600M
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms600m -Xmx1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
  elija:
    image: bp2018hg1/elija:latest
    deploy:
      replicas: ${ELIJA_REPLICAS}
    depends_on:
      - neo4j
      - elasticsearch
    environment:
      - ES_URL=http://elasticsearch:9200
      - FILE_SERVER=${FILE_SERVER_URL}
      - UPLOAD_FOLDER=uploads/
      - NEO4J_URL=bolt://:@neo4j:7687
      - CLOUD_VISION_API_URL=https://vision.googleapis.com/v1/images:annotate
      - CLOUD_VISION_API_KEY=
      - JWT_SECRET_KEY=
      - SECURE_COOKIES=True
    volumes:
      - ${UPLOADS_DIR}:/src/uploads
      - ${WORDKIT_DIR}:/root/nltk_data
    command: ./wait-for.sh neo4j:7687 --timeout=60 -- ./start-gunicorn.sh
  jona:
    image: bp2018hg1/jona:latest
    deploy:
      replicas: ${JONA_REPLICAS}
  tobito:
    image: bp2018hg1/tobito:latest
    deploy:
      replicas: ${TOBITO_REPLICAS}
  files_nginx:
    image: nginx:1.13.12-alpine
    deploy:
      replicas: ${FILES_NGINX_REPLICAS}
    volumes:
      - ./files-nginx.conf:/etc/nginx/conf.d/default.conf
      - ${UPLOADS_DIR}:/files

volumes:
  esdata:
    driver: local
