version: "3"
services:
  main_nginx:
    image: nginx:1.13.12-alpine
    depends_on:
      - jona
      - elija
      - tobito
      - files_nginx
    volumes:
      - ./main-nginx.conf.template:/etc/nginx/conf.d/default.conf.template:ro
      - ${LETSENCRYPT_DIR}:/etc/letsencrypt:ro
    env_file: ./nginx.env
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
  neo4j:
    image: neo4j:3.4.5
    deploy:
      replicas: ${NEO4J_REPLICAS}
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 800M
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ${NEO4J_DIR}:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    deploy:
      replicas: ${ELASTICSEARCH_REPLICAS}
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 600M
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms600m -Xmx1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
  elija:
    image: bp2018hg1/elija:latest
    deploy:
      replicas: ${ELIJA_REPLICAS}
    depends_on:
      - neo4j
      - elasticsearch
    env_file: ./elija.env
    volumes:
      - ${UPLOADS_DIR}:/src/uploads
      - ${WORDKIT_DIR}:/root/nltk_data:ro
      - ${ELIJA_GOOGLE_CREDENTIALS_PATH}:/src/google_credentials.json:ro
    command: ./wait-for.sh neo4j:7687 --timeout=60 -- ./start-gunicorn.sh
  jona:
    image: bp2018hg1/jona:latest
    deploy:
      replicas: ${JONA_REPLICAS}
  tobito:
    image: bp2018hg1/tobito:latest
    deploy:
      replicas: ${TOBITO_REPLICAS}
    env_file: ./tobito.env
    volumes:
      - ${TOBITO_GOOGLE_CREDENTIALS_PATH}:/usr/src/app/google_credentials.json:ro
  files_nginx:
    image: nginx:1.13.12-alpine
    deploy:
      replicas: ${FILES_NGINX_REPLICAS}
    volumes:
      - ./files-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${UPLOADS_DIR}:/files

volumes:
  esdata:
    driver: local
